---
- name: Save Config to Git Repo
  hosts: all
  vars:
    device_config_folder: './configs'
    git_repo: '../config_backup'

  tasks:
  - name: Get Time
    command: date
    register: timestamp
    changed_when: false
    delegate_to: localhost
    run_once: yes

  - name: Create Folder to store config
    file: path={{device_config_folder}}  state=directory
    delegate_to: localhost
    run_once: yes

  - name: Try to switch to target branch
    block:
      - name: switch to target branch
        command: git checkout {{git_branch|default('config_backup')}}
        args:
          chdir: "{{ git_repo }}"
        changed_when: false
          
    rescue:    
      - name: Create and switch to target repo
        command: git checkout -b {{git_branch|default('config_backup')}}
        args:
          chdir: "{{ git_repo }}"
        changed_when: false
    delegate_to: localhost
    run_once: yes

  - name: Syncronize with remote branch
    command: git pull origin master
    args:
      chdir: "{{ git_repo }}"
    changed_when: false
    delegate_to: localhost
    run_once: yes

     
  - name: Get Running Config for Arista
    block:
    - name: Get show running from Arista Devices
      eos_command:
        commands: show running-config
      register: eos_cmd
    - name: copy Runnig configuration to backup folder
      copy:
        content: "{{ eos_cmd.stdout[0] }}"
        dest: "{{device_config_folder}}/{{inventory_hostname}}.cfg"
    when: network_os=='eos'

  - name: Get Running Config from JunOS Nodes
    block:
      - name: Get show running from JunOS Devices
        junos_command:
            commands: show configuration
        register: junos_cmd
      - name: copy Runnig configuration to backup folder
        copy:
          content: "{{ junos_cmd.stdout[0] }}"
          dest: "{{device_config_folder}}/{{inventory_hostname}}.cfg"
    when: network_os=='junos'

  - name: Remove Not needed Lines in the Configuration Files
    lineinfile:
      path: '{{device_config_folder}}/{{inventory_hostname}}.cfg'
      regexp: '## Last .*'
      state: absent
    delegate_to: localhost
        
  - name: Check the directory status
    command: git status
    args:
      chdir: "{{git_repo}}"
    register: changes
    changed_when: false
    delegate_to: localhost
    run_once: yes

  - name: "Add files to Git staging area, commit and push"
    shell: |
      git add .
      git commit -m "Device Backup on {{timestamp.stdout}} "
      git push origin {{git_branch|default('config_backup')}}
    args:
      chdir: "{{git_repo}}"
    when: not("working directory clean" in changes.stdout)
    delegate_to: localhost
    run_once: yes

  - name: return to master branch
    command: git checkout master
    args:
      chdir: "{{git_repo}}"
    changed_when: false
    delegate_to: localhost
    run_once: yes
